// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXR8vqSz5MG45dFFbKWvh-m_xmR4eEZwI',
    appId: '1:780161739686:web:81725d5c1f99611ba0fd67',
    messagingSenderId: '780161739686',
    projectId: 'project-5363883287350640742',
    authDomain: 'project-5363883287350640742.firebaseapp.com',
    storageBucket: 'project-5363883287350640742.firebasestorage.app',
    measurementId: 'G-KXJG8YCE50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Vo_aD8SvIOW5gaPW5Q_RacfRk1HmRqY',
    appId: '1:780161739686:android:85b8d6409a736560a0fd67',
    messagingSenderId: '780161739686',
    projectId: 'project-5363883287350640742',
    storageBucket: 'project-5363883287350640742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBwmX5MzN39kZdbaYaX7P7_dphgVY9ETM',
    appId: '1:780161739686:ios:8f8b41ee200a6c58a0fd67',
    messagingSenderId: '780161739686',
    projectId: 'project-5363883287350640742',
    storageBucket: 'project-5363883287350640742.firebasestorage.app',
    iosBundleId: 'com.example.calkulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBwmX5MzN39kZdbaYaX7P7_dphgVY9ETM',
    appId: '1:780161739686:ios:8f8b41ee200a6c58a0fd67',
    messagingSenderId: '780161739686',
    projectId: 'project-5363883287350640742',
    storageBucket: 'project-5363883287350640742.firebasestorage.app',
    iosBundleId: 'com.example.calkulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXR8vqSz5MG45dFFbKWvh-m_xmR4eEZwI',
    appId: '1:780161739686:web:3cc1b239601d00ffa0fd67',
    messagingSenderId: '780161739686',
    projectId: 'project-5363883287350640742',
    authDomain: 'project-5363883287350640742.firebaseapp.com',
    storageBucket: 'project-5363883287350640742.firebasestorage.app',
    measurementId: 'G-JC84XHBE3F',
  );
}
