name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' 
          channel: 'stable'

      - name: Create .env file
        run: |
          echo "MUX_API_TOKEN=placeholder" >> .env
          echo "MUX_SECRET_KEY=placeholder" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization
        run: flutter gen-l10n

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test